name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build